version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    # cooldown:
    #   semver-patch-days: 900 # the Newtonsoft.Json packages have been published for quite some time
