version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 20
      semver-major-days: 20
      semver-minor-days: 5
      semver-patch-days: 5
